(function() {
  'use strict';

  angular.module('app', [
    'ui.router',
    'ngResource',
    'angular.filter',
    'ngMaterial',
    'ngMessages',
    'ngTable',
    'md.data.table',
    'satellizer',
    'ui.calendar',
    'ngMaterialDatePicker',
    'ui.bootstrap.datetimepicker',
    //'templates',
    'app.config',
    'app.inicio',
    'app.footer',
    'app.header',
    'app.admin',
    'app.login',
    'app.auditacitas',
    'app.paciente',
    'app.recepcionista',
    'app.usuarios',
    'app.fisioterapeuta',
    'app.auditausuarios',
    'app.clinicas',
    'app.consultorios',
    'app.sedes',
    'app.ocupaciones',
    'app.peratiende',
    'app.tiantecedentes',
    'app.pertratante',
    'app.antecedentes',
    'app.funcionarios',
    'app.citas',
    'app.entidades',
    'app.password.recovery',
    'app.password.confirm',
    'app.cexternas'
  ]);

})();
